// swift-tools-version: 5.6

// WARNING:
// This file is automatically generated.
// Do not edit it by hand because the contents will be replaced.

import PackageDescription
import AppleProductTypes

let package = Package(
    name: "Arkom",
    platforms: [
        .iOS("15.2")
    ],
    products: [
        .iOSApplication(
            name: "Arkom",
            targets: ["AppModule"],
            bundleIdentifier: "Panuwat.Arkom.app",
            teamIdentifier: "HRN53UGUKN",
            displayVersion: "0.1.0",
            bundleVersion: "1",
            appIcon: .asset("AppIcon"),
            accentColor: .asset("AccentColor"),
            supportedDeviceFamilies: [
                .pad,
                .phone
            ],
            supportedInterfaceOrientations: [
                .portrait,
                .landscapeRight,
                .landscapeLeft,
                .portraitUpsideDown(.when(deviceFamilies: [.pad]))
            ],
            capabilities: [
                .speechRecognition(purposeString: "Arkom Want to acess your speech recognition to detect English text to speech "),
                .microphone(purposeString: "Arkom Want to acess your microphone to detect English text to speech ")
            ],
            appCategory: .actionGames
        )
    ],
    targets: [
        .executableTarget(
            name: "AppModule",
            path: ".",
            resources: [
                .process("Resources")
            ]
        )
    ]
)